apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: notes-app-ingress

spec:
  ingressClassName: nginx

  rules:
  - host: notes-app.local

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: django-service

            port:
              number: 8000
